# Generated by Django 6.0 on 2025-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_post_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
